//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_Direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_Direccion()
        {
            this.c_Programa_Edu = new HashSet<c_Programa_Edu>();
        }
    
        public int id_direccion { get; set; }
        public string nombre { get; set; }
        public string siglas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_Programa_Edu> c_Programa_Edu { get; set; }
    }
}
