//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int id_evento { get; set; }
        public string codigo { get; set; }
        public Nullable<int> matricula_co { get; set; }
        public int id_estado { get; set; }
        public string ponente { get; set; }
        public string titulo { get; set; }
        public System.DateTime fecha { get; set; }
        public string lugar { get; set; }
        public string asesor { get; set; }
        public int id_tipo { get; set; }
        public string abstracto { get; set; }
    
        public virtual c_Estado_Evento c_Estado_Evento { get; set; }
        public virtual c_Tipo_Evento c_Tipo_Evento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
