//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAEPEntities : DbContext
    {
        public SAEPEntities()
            : base("name=SAEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<c_Direccion> c_Direccion { get; set; }
        public virtual DbSet<c_Estado_Evento> c_Estado_Evento { get; set; }
        public virtual DbSet<c_Programa_Edu> c_Programa_Edu { get; set; }
        public virtual DbSet<c_Rol> c_Rol { get; set; }
        public virtual DbSet<c_Tipo_Evento> c_Tipo_Evento { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
